### ISSUE TITLE
Withdrawing Problems..

### ISSUE THREAD

**Issue by ErraticGalaxy** [JustEli/Coins#1]
Love the plugin, but there is a problem with it. When I withdraw and drop a coin on the ground, I can't pick it back up.. Also when I right click on the ground with it, it turns into a flower but it's still in your inventory. Not something major, but thought it should get fixed. Thanks!

**Comment by JustEli** [comment]
Thanks!

> Also when I right click on the ground with it, it turns into a flower but it's still in your inventory. 

A withdrawn coin is meant to be dropped, and after you pick it up, the money should be collected and the coin should disappear. But as you say

> I can't pick it back up..

Your inventory may have been full. That's the only reason I can think of really. 
Or maybe you aren't op, but have the '*' permission instead, but that would mean that you wouldn't be able to pick up any coins.
At least it still works on my server, and I haven't changed a thing in the config, so maybe there's some error with the config. 
Does the console give any errors?

**Comment by ErraticGalaxy** [comment]
No my inventory was completely empty. Are you not allowed to pick up coins if you aren’t op and have the ‘*’ permission? Because that is exactly what it was, as soon as I op myself it started working. How would I get around this? Or is there no way to get around it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JustEli** [comment]
Because in the code:
```
if (!e.getPlayer().hasPermission("coins.disable") || e.getPlayer().isOp())
	giveCoin(item, e.getPlayer(), item.getItemStack().getAmount() * amount);
```
Which means:
if the player doesn't have permission "coins.disable" or the player is op; give the coin
This excludes players with '*'. :p 

I'll add '*' quickly to the code and PM you the updated plugin.

**Comment by ErraticGalaxy** [comment]
I kinda feel like a tard now, thanks man

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JustEli** [comment]
lol, it's nice for me too to have that fixed now, it kindof was a missing thing.
[Coins 1.2.1.zip](https://github.com/JustEli/Coins/files/816572/Coins.1.2.1.zip)

Warn me when it doesn't work.

**Comment by ErraticGalaxy** [comment]
Works now!
