### ISSUE TITLE
Infinite coins glitch 

### ISSUE THREAD

**Issue by freethemice** [JustEli/Coins#10]
If you are able to pick up coins into your inventory, place some in your off hand and while in the inventory screen, left click on the coins as if to pick them back up. it will give you the money but won't take the coins out of your off hand. Placing coins into your inventory is easy too. use an hopper to pick them up and then right click to pick up half the stack from the hopper/connected chest

**Comment by JustEli** [comment]
hi, i don't understand your first part: "and while in the inventory screen, left click on the coins as if to pick them back up"

**Comment by JustEli** [comment]
and it sounds like it is a bug that has to do with Spigot

**Comment by freethemice** [comment]
This isn’t a spigot bug, how is that. 
If you have your inventory screen open left click the coins, that’s are in your off hand, and it will give you the money and leave the coins. 

I have my own plugin that I made a work around with so I know it’s not a spigot bug.

**Comment by JustEli** [comment]
found it, will fix asap

**Comment by JustEli** [comment]
thanks for reporting that!!

**Comment by JustEli** [comment]
i still think it is a bug with spigot though, but i will do my best

**Comment by JustEli** [comment]
will delete this issue to prevent other players to read it, for safety reasons on servers who still use older versions
