### ISSUE TITLE
Right Click Bug

### ISSUE THREAD

**Issue by WarenGonzaga** [JustEli/Coins#14]
When you right-click on the grass the sunflower will be planted. As shown in the picture below.
http://prntscr.com/pw8wwi

**Comment by JustEli** [comment]
yeah i know
i've been looking into this, but this is a "bug" with bukkit/spigot themself, or even minecraft

you'd also get this if you're i,e, in a WG region you don't have build permission at: when and plant any double plant. it will also keep the top block
