### ISSUE TITLE
Magic from plugin "wands" does not result in coin drop

### ISSUE THREAD

**Issue by pdglobal** [JustEli/Coins#16]
Would it be possible to add a configuration option for mobs to always drop coins regardless of death cause?

I ask because on my server we use the wands plugin, and when a mob is killed via a spell, it seems the coins are not dropped because the kill is not linked directly to the player casting the spell(s)

**Comment by JustEli** [comment]
i'll not be hooking into plugins, but, yeah, i could possibly add a config option for mobs to always drop coins, i'll add it to my to-do list, but expect me to take a while to add it heh

**Comment by pdglobal** [comment]
Okay, I can wait, but yeah if you could just make an option to always drop the coins regardless of death reason, that would be fantastic ^_^

**Comment by JustEli** [comment]
nvm i added it anyways right now, thanks for your patience xD
