### ISSUE TITLE
No drop for ores that does not drop an item & no money removed after kill

### ISSUE THREAD

**Issue by bertugarangou** [JustEli/Coins#24]
**Describe the bug**
Mining ores like IRON, GOLD, or non-item-dropping XP blocks that should drop a coin, does not drop any coin.

**To Reproduce**
Mine iron or gold for example, with an iron or diamond pickaxe. It won't drop coins neither putting the iron_ore into the furnace. Coal and diamond ore when mining it does drop coins. 

**Expected behavior**
To mine iron or gold and getting a coin.

**System**
 - PaperMC last version till today: git-paper 135, MC1.16.1, plugin: 1.9.5

In the config file it is set to drop just for XP blocks (such as iron, as it is written) and 1.0 chance of dropping for mining.
[config.yml](https://hastebin.com/ilawubecas.makefile)

UPDATE: 
just discovered that when dying it does not reduces the money.

**Comment by JustEli** [comment]
actually, it will only drop coins for mining blocks that drop experience, 
i see that i made a mistake in the config by saying iron is such block, but it isn't as it drops no experience
