### ISSUE TITLE
Potential issues with skull items with custom textures

### ISSUE THREAD

**Issue by blablubbabc** [JustEli/Coins#29]
A user of the Shopkeepers plugin ran into issues with his custom skull items created by this plugin not working in villager trades created by the Shopkeepers plugin, so I looked into it and noticed a few potential issues with these skull items with custom textures:

* https://github.com/JustEli/Coins/blob/ec50d594b05c450b8ed03cd433ef0c0e3e3bee23/src/main/java/me/justeli/coins/api/SkullValue.java#L41 You give each new item a profile with a new random uuid. This will make these items unique and cause them to not stack, and also to not properly work in villager trades.
However, this is not actually an issue until you reload the server/plugin, because you seem to cache previously created skull items (and thereby you also cache and reuse this random profile uuid): https://github.com/JustEli/Coins/blob/ec50d594b05c450b8ed03cd433ef0c0e3e3bee23/src/main/java/me/justeli/coins/api/SkullValue.java#L31 However, this cache is not persisted. So for this to become an issue, and for you to reproduce that this is an issue, you need to: Create an item (eg. via the `/withdraw` command); items created by subsequent withdrawals will stack with the previously withdrawn items due to this cache; then fully reload the plugin (/reload command) or restart the server; items created by subsequent withdrawals after this reload will not stack with items that have been withdrawn earlier (before the reload).
* https://github.com/JustEli/Coins/blob/ec50d594b05c450b8ed03cd433ef0c0e3e3bee23/src/main/java/me/justeli/coins/api/SkullValue.java#L60 You seem to only set the item meta's profile field. However, there is also the field 'serializedProfile', which is meant to be consistent with the profile (https://image.prntscr.com/image/DwiYDDtgRluOlL_ghDRLDQ.png). This field got added roughly a year ago (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/82322fe06c1331a4fc0d31b062ed633c99fce004#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java).
Right now this does not seem to cause issues in combination with the Shopkeepers plugin, because Spigot _happens_ to synchronize the 'profile' and 'serializedProfile' fields (as a side effect of the method which fills in missing texture data) when the item meta gets applied to an actual Minecraft item (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java#92). However, in principal this might cause issues nevertheless (for example if the items get somehow passed to another plugin without this intermediate conversion to a Minecraft ItemStack and then back to a (Craft)Bukkit ItemStack; or if this item gets serialized without this prior synchronization of these fields).
An option could be for you to use the method 'setProfile' instead (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java#81).

I don't know whether fixing these issues will resolve the issue that this other user of the Shopkeepers plugin had. This are just the things that I have noticed so far while looking into this. But my current guess is that the first issue mentioned above is the one relevant to this user.

Here is the config which I tested this with: https://pastebin.com/znve6tyV

**Comment by joex92** [comment]
I'm the user mentioned here... thanks @blablubbabc for even explaining why the issue was happening, I didn't know this was an issue with this plugin, I thought it was a Shopkeeper issue in the beginning...  anyways...
for now I had to remove the `skullTexture` and use enchanted emeralds, but that should not be an option, after all the head texture had a meaning with the server's theme... but anyways... I hope you get to solve this because I like this plugin a lot...

**Comment by JustEli** [comment]
i'll look into this next week!

**Comment by JustEli** [comment]
in 1.10.2 i made it so the uuid of head-coins will always be `00000001-0001-0001-0001-000000000002`, do you think that'll fix the issue? gonna publish 1.10.2 later today

**Comment by blablubbabc** [comment]
I have compiled the plugin and briefly tested this, and it seems to work fine. Thanks!
