### ISSUE TITLE
Money/Coin didn't drop after player dead

### ISSUE THREAD

**Issue by martin1194** [JustEli/Coins#30]
Money/Coin didn't drop after player dead.

Minecraft Version: 1.12.2
Server: Magma-50f320e-server
OS: Windows 10

[config.yml.txt](https://github.com/JustEli/Coins/files/5647339/config.yml.txt)

**Comment by JustEli** [comment]
players aren't supposed to drop coins unless you configure it right

**Comment by martin1194** [comment]
Sorry. I uploaded wrong. 
I upload to youtube now.
https://www.youtube.com/watch?v=J1CGW4uQxk8&feature=youtu.be

This yml is the real version. 
[config.yml.txt](https://github.com/JustEli/Coins/files/5647494/config.yml.txt)

**Comment by martin1194** [comment]
Item seem only kill player will drop money. But never drop if killed by zombie or other monster

**Comment by JustEli** [comment]
oh i thought this was working fine all this time, found out it didn't today, but it should be fixed in 1.10.3
