### ISSUE TITLE
wider pitch range

### ISSUE THREAD

**Issue by joex92** [JustEli/Coins#32]
Hi, I don't know if this is possible but 
it would be great if `soundPitch` could be set greater than 2 and lesser than 0.5 (but never 0 or less obviously)... 
for a better experience... maybe it could be set between 0.25(1/4) and 4, or 0.125(1/8) and 8... that would be wide enough...

**Comment by JustEli** [comment]
can't you already put `soundPitch` to whatever you want?
if `soundPitch: 2` doesn't work, maybe try `soundPitch: 2.0`

**Comment by joex92** [comment]
It works between 0.5 and 2.0
but I wanted to make it even higher, like 2.5 or 3.0... but it doesn't work, when setting it to a value higher than 2, it keeps sounding like the 2.0 value... same for values lower than 0.5, if I set it to 0.25 it sounds the same as 0.5...

**Comment by JustEli** [comment]
well then that is minecraft's limitation

**Comment by joex92** [comment]
oh ok... I thought that maybe It could be set higher...
