### ISSUE TITLE
setting up coins for gemseconomy

### ISSUE THREAD

**Issue by cheez568** [JustEli/Coins#37]
Hello. I've been having a problem with setting up this plugin with gemseconomy (https://www.spigotmc.org/resources/gemseconomy.19655/) i just want to know how to set up this plugin with coins to work properly

plugin: AnnouncementsEverywhere, ChestShop, Coins, CoreProtect, Essentials, GemsEconomy, Geyser-Spigot, GriefPrevention, LuckPerms, TogglePvp, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, placeholderAPI

it works on essential but i want change it to GemsEconomy

Thanks

**Comment by JustEli** [comment]
problem solved?
