### ISSUE TITLE
Players are able to create their coin using rename command and recolor command and abuse the system

### ISSUE THREAD

**Issue by wazerpro** [JustEli/Coins#39]
Players are able to create their own coin of any amount if they use rename and recolor command. Can you make the item unique with NBT Tag or something? so no one can recreate coins using rename and recolor command? I feel like the plugin just identifies coins just by name and color. it's not even detecting item differences. I can rename an arrow as 100000 Coins for example and it will still be redeemable. Thanks for reading my terrible issue report. Have a nice day.

**Comment by JustEli** [comment]
that's correct. it is not vanilla behaviour to rename items to names with color. i also can't fix this in 1.x because that will make existing withdrawn coins worthless. i already have this fixed in 2.x however, which is a rewrite i'm working on
