### ISSUE TITLE
Placing a sunflower when a coin is used on grass/dirt

### ISSUE THREAD

**Issue by MarkGDK** [JustEli/Coins#42]
**Describe the bug**
When right-clicking a default coin (sunflower) on a grass/dirt block it places a sunflower.

**To Reproduce**
1. Use the coin on a grass/dirt block
2. The sunflower gets placed.

**Expected behavior**
The coins should not plant a sunflower like when it's used on other blocks.

**Screenshots**
https://snipboard.io/ZNlbvH.jpg

**System**
 - OS: Windows 10 Enterprise 21H1

**Error**
None

**Additional context**
None

**Comment by JustEli** [comment]
#8
