### ISSUE TITLE
Huge amounts of lag when using custom heads

### ISSUE THREAD

**Issue by Rixic** [JustEli/Coins#45]
**Describe the bug**
Lag spikes for coin drops using custom player head texture

**To Reproduce**
Use a custom skull texture, have drop each coin on and even with 5 coins it will lag

**Expected behavior**
No lag spike

**Screenshots**

**Additional context**
https://timings.aikar.co/?id=89d00c4e756943b8b4eec9383ece6cb3#timings

**Comment by JustEli** [comment]
caused by DropHeads (listens to coin drops)
