### ISSUE TITLE
Ability to set "minimum" withdraw amount.

### ISSUE THREAD

**Issue by tdeverx** [JustEli/Coins#48]
**Is your feature request related to a problem? Please describe.**
My idea was to use fake bitcoin as my currency, but I cant withdraw an amount less than 1. 

For example, bitcoin (satoshi) is moved 8 decimal places, so $1 = 0.00002700 satoshi.

**Describe the solution you'd like**
I'd love to be able to set the minimum withdraw amount to a number less than 1.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JustEli** [comment]
will be fixed in the next version, which may take days to weeks to release

**Comment by JustEli** [comment]
actually, here you go
[Coins-1.12.1.zip](https://github.com/JustEli/Coins/files/7999125/Coins-1.12.1.zip)

**Comment by tdeverx** [comment]
WOW, that was fast hahaha! Thank you very much 👍
