### ISSUE TITLE
Death Error

### ISSUE THREAD

**Issue by freethemice** [JustEli/Coins#7]
`22.01 19:13:03 [Server] ERROR Could not pass event PlayerDeathEvent to Coins v1.7.1
22.01 19:13:03 [Server] INFO org.bukkit.event.EventException: null
22.01 19:13:03 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:614) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:515) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:820) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:655) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.c(EntityLiving.java:1375) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityHuman.c(EntityHuman.java:1644) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.Block.fallOn(Block.java:582) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.Entity.a(Entity.java:1097) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityLiving.a(EntityLiving.java:208) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.EntityPlayer.a(EntityPlayer.java:832) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1085) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
22.01 19:13:03 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
22.01 19:13:03 [Server] INFO Caused by: java.lang.NullPointerException
22.01 19:13:03 [Server] INFO at me.justeli.coins.events.DropCoin.onDeath(DropCoin.java:53) ~[?:?]
22.01 19:13:03 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source) ~[?:?]
22.01 19:13:03 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-488]
22.01 19:13:03 [Server] INFO ... 26 more`

**Comment by wolvfang** [comment]
Sorry for the delayed response, I will look into this error later when I am at home and see if I can reproduce/fix it

**Comment by JustEli** [comment]
Do you have an economy supportive plugin like Essentials or iConomy installed? Seems like you're missing that.

**Comment by JustEli** [comment]
Or can you send me the FULL list of all the plugins on the server?

**Comment by JustEli** [comment]
@freethemice Can you?

**Comment by freethemice** [comment]
I got it fixed. I think I just added my economy plugin to the dependence in the plugin yml 
I’m using the Aconomy plugin
