### ISSUE TITLE
Placing Coin 1/2 Flower

### ISSUE THREAD

**Issue by freethemice** [JustEli/Coins#8]
When you withdraw a coin, if you place it, it will put the top half of the sunflower and leave the coin in your inventory.w

**Comment by wolvfang** [comment]
Sorry for the late response, I will look into this later when I get time

**Comment by wolvfang** [comment]
Sorry for the late response, I will look into this later when I get time

**Comment by JustEli** [comment]
This is a bug on Mojang's side. There's no way I can fix this.
