### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by mirineserver** [JustEli/Coins#9]
Loads faster than dependency plugins.

**Comment by wolvfang** [comment]
Sorry for the very late response, are you still having thus problem with Coins
If you are, please can you provide some more information such as your server version, the dependencies that are loading after Coins and any errors in the console

**Comment by mirineserver** [comment]
vault and playerpoints
1.13.2.

>

**Comment by JustEli** [comment]
What's your problem here?

**Comment by mirineserver** [comment]
It is slower to load the plugin than its dependencies. It is a very fatal
error and makes it impossible to use!

2019년 3월 7일 (목) 05:04, Eli, wyldt- <notifications@github.com>님이 작성:

**Comment by wolvfang** [comment]
Just ran a server using latest spigot and coins w/ vault and essentials for the economy (not 100% sure what playerpoints is, but from a quick search it doesn't appear to be something that would be a dependency for Coins) and it's all loading in the right order for me, could you provide an output of your console log?

(You can get your latest console log from the logs folder which is in the same place as the plugins folder and server jar)
